In [84]:
import  os  
os.getcwd()

'C:\\Users\\Admin\\pandas'

In [1]:
#  if  data set  present  in  same folder  you can use  only name  like mussoorie_cleaned.csv in pd.read_csv() ,no need  of  location like a\\b\\c

In [2]:
import  pandas  as  pd  
df3 = pd.read_csv("C:\\Users\\Admin\\pandas\\mussoorie_cleaned.csv")
df3

,place,description,extra_details
0,Lal Tibba,"Lal Tibba , Lal Tibba stands as Mussoorie's hi...","Perched at 2,275 meters"
1,Kempty Falls,Kempty Falls unfolded a mesmerizing tapestry ...,heart of Mussoorie
2,Gun Hill,"Gun Hill Perched atop Mussoorie, Gun Hill echo...",second-highest peak in the region
3,The Mall Road,"The Mall Road, invites you to a. Lined with vi...",delightful dance of shopping and strolling
4,Company Garden,Company Garden unveils a canvas of vibrant. As...,blooms and tranquil serenity
5,Mussoorie Lake,Mussoorie Lake unveils a haven of serenity. As...,Mussoorie Lake
6,Benog Wildlife Sanctuary,Benog Wildlife Sanctuary The Benog Wildlife Sa...,Not available
7,Landour,Landour is a colonial gem frozen in time. Cobb...,vintage charm
8,Jharipani Falls,Jharipani Falls is Mussoorie's hidden treasure...,nature's melody
9,Cloud's End,"Cloud's End Mussoorie, Cloud's End is a. Surro...",haven of serenity
10,Nag Tibba,Nag Tibba Embarking on the Nag Tibba trek in t...,mystical hills of Mussoorie
11,Camel's Back Road,Camel's Back Road invites wanderers to a leisu...,haven for peace-seekers

In [86]:
df2 = pd.read_csv("C:\\Users\\Admin\\pandas\\shoes_2000_to_5000.csv")

In [87]:
df2 = df2.rename(columns=lambda col: (
    col.replace("CIaYa1 href", "product_link")
       .replace("MZeksS src", "image_url")
       .replace("Fo1I0b", "brand")
       .replace("atJtCj href", "product_page")
       .replace("atJtCj", "product_name")
       .replace("Q3Sg7S src", "extra_image")
       .replace("hZ3P6w", "price")
       .replace("kRYCnD", "original_price")
       .replace("HQe8jr", "discount")
       .replace("HZ0E6r", "rating")
       .replace("yZLfgx", "size_options")
       .replace("g_3iVf", "size_label")
))

In [88]:
print(df2.columns.to_list())

['product_link', 'image_url', 'brand', 'product_name', 'product_page', 'extra_image', 'price', 'original_price', 'discount', 'product_link 2', 'image_url 2', 'brand 2', 'product_name 2', 'product_page 2', 'price 2', 'original_price 2', 'discount 2', 'rating', 'product_link 3', 'image_url 3', 'brand 3', 'product_name 3', 'product_page 3', 'price 3', 'original_price 3', 'discount 3', 'rating 2', 'product_link 4', 'image_url 4', 'brand 4', 'product_name 4', 'product_page 4', 'extra_image 4', 'price 4', 'rating 3', 'size_options', 'size_label', 'rating 4']

In [89]:
df2.head(2)

,product_link,image_url,brand,product_name,product_page,extra_image,price,original_price,discount,product_link 2,...,image_url 4,brand 4,product_name 4,product_page 4,extra_image 4,price 4,rating 3,size_options,size_label,rating 4
0,https://www.flipkart.com/asics-gel-contend-4b-...,https://rukminim2.flixcart.com/image/612/612/x...,Asics,GEL-CONTEND 4B+ Running Shoes For Men,https://www.flipkart.com/asics-gel-contend-4b-...,https://static-assets-web.flixcart.com/fk-p-li...,"₹1,999","₹4,299",53% off,https://www.flipkart.com/asics-gel-nimbus-27-r...,...,https://rukminim2.flixcart.com/image/612/612/x...,NIKE,Revolution 8 Running Shoes For Men,https://www.flipkart.com/nike-revolution-8-run...,https://static-assets-web.flixcart.com/fk-p-li...,"₹4,295",Only few left,"7, 8, 11, 12",Size,NaN
1,https://www.flipkart.com/nike-revolution-8-run...,https://rukminim2.flixcart.com/image/612/612/x...,NIKE,Revolution 8 Running Shoes For Men,https://www.flipkart.com/nike-revolution-8-run...,https://static-assets-web.flixcart.com/fk-p-li...,"₹4,295","₹14,999",62% off,https://www.flipkart.com/nike-promina-walking-...,...,https://rukminim2.flixcart.com/image/612/612/x...,Asics,SUPERBLAST 2 Running Shoes For Men,https://www.flipkart.com/asics-superblast-2-ru...,https://static-assets-web.flixcart.com/fk-p-li...,"₹21,999",Hot Deal,"7, 8, 9, 10, 11",Size,NaN

In [90]:
df2 = df2.drop(columns=[col for col in df2.columns if 'link' in col or 'image' in col or 'page' in col])

In [91]:
import pandas as pd

# Step 1: Convert wide → long
final_data = []

for i in range(len(df2)):
    row = df2.iloc[i]
    
    for j in ['', ' 2', ' 3', ' 4']:
        try:
            name = row[f'product_name{j}']
            brand = row[f'brand{j}']
            price = row[f'price{j}']
            original_price = row.get(f'original_price{j}', None)
            discount = row.get(f'discount{j}', None)
            
            if pd.notna(name):
                final_data.append([name, brand, price, original_price, discount])
        
        except:
            continue

# Step 2: Create DataFrame
final_df = pd.DataFrame(final_data, columns=[
    'product_name', 'brand', 'price', 'original_price', 'discount'
])

# Step 3: Create numeric columns (keep original also)
final_df['price_num'] = final_df['price'].str.replace('₹', '').str.replace(',', '').astype(float)

final_df['original_price_num'] = final_df['original_price'].str.replace('₹', '').str.replace(',', '').astype(float)

final_df['discount_num'] = final_df['discount'].str.replace('% off', '').astype(float)
final_df = final_df.drop(columns=['original_price_num', 'discount_num','price_num'])

final_df['original_price'] = final_df['original_price'].fillna("Not Available")
final_df['discount'] = final_df['discount'].fillna("No Discount")

final_df = final_df.drop_duplicates()
# Step 4: Output
final_df

,product_name,brand,price,original_price,discount
0,GEL-CONTEND 4B+ Running Shoes For Men,Asics,"₹1,999","₹4,299",53% off
1,GEL-NIMBUS 27 Running Shoes For Men,Asics,"₹13,599","₹16,999",20% off
2,PATRIOT 13 Running Shoes For Men,Asics,"₹4,399","₹5,499",20% off
3,Revolution 8 Running Shoes For Men,NIKE,"₹4,295",Not Available,No Discount
4,Revolution 8 Running Shoes For Men,NIKE,"₹4,295","₹14,999",62% off
5,Promina Walking Shoes For Men,NIKE,"₹4,995",Not Available,No Discount
6,GEL-JADEITE 3 Running Shoes For Men,Asics,"₹5,699",Not Available,No Discount
7,SUPERBLAST 2 Running Shoes For Men,Asics,"₹21,999",Not Available,No Discount
8,Shoes for Men | Sneaker for Men | Sports Shoes...,NIKE,"₹4,895","₹11,999",20% off
9,Running Shoes For Men,NIKE,"₹4,295","₹4,499",50% off
10,GEL-CUMULUS 27 Running Shoes For Men,Asics,"₹9,599",Not Available,No Discount
11,JOLT 1 Running Shoes For Men,Asics,"₹2,249",Not Available,No Discount
12,GT-2000 13 Running Shoes For Men,NIKE,"₹4,542","₹8,995",49% off
13,Training & Gym Shoes For Men,Asics,"₹10,399","₹12,999",20% off
14,Running Shoes For Men,NIKE,"₹4,669","₹8,895",47% off
15,Running Shoes For Men,NIKE,"₹4,396",Not Available,No Discount
16,GEL-CUMULUS 27 Running Shoes For Men,Asics,"₹9,599","₹11,999",20% off
17,GEL-PEAKE 2 Cricket Shoes For Men,Asics,"₹6,399","₹7,999",20% off
19,NIKE REVOLUTION 7 Running Shoes For Men,NIKE,"₹3,695",Not Available,No Discount
20,GEL-EASE Running Shoes For Men,Asics,"₹2,799","₹6,999",60% off
21,GEL - EASE Running Shoes For Men,Asics,"₹2,799","₹6,999",60% off
22,Revolution 8 Running Shoes For Men,NIKE,"₹4,295","₹3,995",22% off
23,NIKE RUN DEFY Running Shoes For Men,NIKE,"₹3,116",Not Available,No Discount
24,M NIKE LEGEND ESSENTIAL 3 NN Training & Gym Sh...,NIKE,"₹3,496","₹4,995",30% off
25,Revolution 7 Running Shoes For Men,NIKE,"₹3,695","₹4,999",50% off
26,GEL-33 RUN Running Shoes For Men,Asics,"₹2,499","₹12,999",20% off
27,GEL-CUMULUS 27 Running Shoes For Men,Asics,"₹10,399",Not Available,No Discount
28,Promina Walking Shoes For Men,NIKE,"₹3,996","₹4,995",20% off
29,Revolution 7 Running Shoes For Men,NIKE,"₹3,695","₹8,999",20% off
30,GEL-PULSE 16 Running Shoes For Men,Asics,"₹7,199",Not Available,No Discount
31,METASPEED SKY TOKYO Running Shoes For Men,Asics,"₹24,999",Not Available,No Discount
32,NIKE RUN DEFY Running Shoes For Men,NIKE,"₹3,995","₹5,695",20% off
33,NIKE RUN DEFY Running Shoes For Men,NIKE,"₹3,995",Not Available,No Discount
34,NIKE PRECISION VII Basketball Shoes For Men,NIKE,"₹4,556",Not Available,No Discount
35,NIKE FLY.BY MID 3 Basketball Shoes For Men,NIKE,"₹4,995",Not Available,No Discount
36,GT-1000 13 Running Shoes For Men,Asics,"₹7,999","₹9,999",20% off
37,GEL-PULSE 16 Running Shoes For Men,Asics,"₹7,199","₹8,999",20% off
39,NIKE JUNIPER TRAIL 3 Running Shoes For Men,NIKE,"₹5,246",Not Available,No Discount

In [224]:
df = pd.read_csv("C:\\Users\\Admin\\pandas\\covid_toy - covid_toy.csv")
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [225]:
# how  we check  how  many  columnes in this  data frame ?
df.columns
# df.columns.value_counts()

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [226]:
# how can  we check  top  5 data from  the  dataframe ?
df.head() # by  default give  5 
df.head(2) # this wil  give  2 row

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [227]:
# removes last 9 rows from DataFram
df.head(-9)

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
86   25    Male  104.0    Mild  Bangalore       Yes
87   47    Male  101.0  Strong  Bangalore        No
88    5  Female  100.0    Mild    Kolkata        No
89   46    Male  103.0  Strong  Bangalore        No
90   59  Female   99.0  Strong      Delhi        No

[91 rows x 6 columns]

In [228]:
# how can  we check  bottom  data from  the  dataframe ?

# By default: returns last 5 rows
df.tail()

    age  gender  fever   cough       city has_covid
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [229]:
# Positive value: returns last n rows (e.g., last 3 rows)
df.tail(3)

    age  gender  fever   cough       city has_covid
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [230]:
# Negative value: returns all rows except first n rows (e.g., skip first 3 rows)
df.tail(-3)

    age  gender  fever   cough       city has_covid
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
5    84  Female    NaN    Mild  Bangalore       Yes
6    14    Male  101.0  Strong  Bangalore        No
7    20  Female    NaN  Strong     Mumbai       Yes
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[97 rows x 6 columns]

In [231]:
df.tail(0) # no  row show

Empty DataFrame
Columns: [age, gender, fever, cough, city, has_covid]
Index: []

In [232]:
df.head(1000)   # if  u  have  100  rows  and  pass  long then  print  full  data set 

# Empty DataFrame in both 
# df3.head(-1000)   ,df.tail(-1000)

-0 == 0
df.head(0)  # → Empty DataFrame  
df.tail(0)  # → Empty DataFrame

Empty DataFrame
Columns: [age, gender, fever, cough, city, has_covid]
Index: []

In [233]:
# -0	Same as 0 → Empty
# -n > rows	Empty DataFrame

In [234]:
df.sample()
df.sample(0)
df.sample(3)
# no negatvie value pass here

    age  gender  fever   cough     city has_covid
25   23    Male    NaN    Mild   Mumbai        No
3    31  Female   98.0    Mild  Kolkata        No
44   20    Male  102.0  Strong    Delhi        No

In [235]:
# how can we check data type of all columns 
df.dtypes  #(object =  means categorical  type data )

age            int64
gender        object
fever        float64
cough         object
city          object
has_covid     object
dtype: object

In [236]:
# how can we cheeck  static view  of dataframe? or mathematical structure
df.describe()

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [237]:
# count =  total  number of entries  

# let suppose 4 values in whhich  1 is none or missing then
# count    3

# 👉 Why 3?

# Total rows = 4
# But one value is None (missing)
# ✔ So count = 3

# “Mean is the average of non-null values in a numeric column.”

# “Standard deviation is the square root of variance and shows how much data is spread around the mean.”


# values = [10, 20, 30, 40, 50]
# 10   20   30   40   50
# |----|----|----|----|
     # ↑    ↑    ↑
    # 25%  50%  75%

# max = largest value in the column (no value above this in current data)

In [238]:
# df['age'].max()

In [239]:
# how can we check  overall  innformation in the  dataframe ?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [240]:
# how can we check  mising values in df?
df.isnull().sum()
# df.isnull()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [241]:
df['fever'].mean()

np.float64(100.84444444444445)

In [242]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [243]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [244]:
# how can we  check  total  sub-categories(values)  in columns  
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [245]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [246]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [247]:
df['has_covid'].value_counts()

has_covid
No     55
Yes    45
Name: count, dtype: int64

In [248]:
df['gender'] =  df['gender'].map({'Male':0,'Female':1})

In [251]:
df['cough'] =  df['cough'].map({'Mild':0,'Strong':1})
df['city'] =  df['city'].map({'Kolkata':0,'Bangalore':1,'Delhi':3,'Mumbai':4})
df['has_covid'] =  df['has_covid'].map({'Yes':0,'No':1})   # if  any  columns  2  time  execute then  nan  so solution execute from  read_csv() or starting

In [250]:
df

    age  gender  fever  cough  city  has_covid
0    60       0  103.0      0     0          1
1    27       0  100.0      0     3          0
2    42       0  101.0      0     3          1
3    31       1   98.0      0     0          1
4    65       1  101.0      0     4          1
..  ...     ...    ...    ...   ...        ...
95   12       1  104.0      0     1          1
96   51       1  101.0      1     0          0
97   20       1  101.0      0     1          1
98    5       1   98.0      1     4          1
99   10       1   98.0      1     0          0

[100 rows x 6 columns]

In [ ]:
# Data --->

# Categorical (Discrete) ---> We cannot divide further.
# Ex. has_covid (y,n), marital_status (y,n), result (p,f),
# students_in_class (50,51)

# Numerical (Continuous) ---> We can divide further.
# Ex. distance jaipur to delhi (310.60 km), weight (kg, gm),
# salary (rupees), insurance_charges (rupees), birth_year (25)

# Key Point:
# Cannot be divided further
# No mathematical meaning