In [2]:
import  pandas as pd

In [3]:
import  os  
os.getcwd()

'C:\\Users\\Admin\\pandas'

In [6]:
df = pd.read_csv('C:\\Users\\Admin\\pandas\\covid_toy - covid_toy.csv')
df.head()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [278]:
# # loc() and Iloc()
# # df.loc(row_range,column_name) or (numeric,cate)---> start value  include  and  last  value include. 
# # df.iloc(row_range,column_range) or (numeric,numeric) ------> start value include   but  last  value  exclude.

# # or 
# df.loc[row_labels, column_labels]   # end INCLUDED
# "loc uses labels, not positions. Even if numbers are used, they are treated as labels."

# # iloc
# df.iloc[row_positions, column_positions]   # end EXCLUDED

In [279]:
# Range (0:2)
df.loc[0:2]
# Exact rows ([1,2])
df.loc[[1,2]]
#2. Column Selection
# Single column
df.loc[:,'gender']
# Multiple columns
df.loc[:, ['city', 'age']]

         city  age
0     Kolkata   60
1       Delhi   27
2       Delhi   42
3     Kolkata   31
4      Mumbai   65
..        ...  ...
95  Bangalore   12
96    Kolkata   51
97  Bangalore   20
98     Mumbai    5
99    Kolkata   10

[100 rows x 2 columns]

In [280]:
df.loc[0:2, ['city','age']]  # 0:2 is show 0,1,2

      city  age
0  Kolkata   60
1    Delhi   27
2    Delhi   42

In [281]:
df.loc[df['age'] > 50, 'city']

0       Kolkata
4        Mumbai
5     Bangalore
9         Delhi
10        Delhi
11       Mumbai
13    Bangalore
14    Bangalore
15      Kolkata
16      Kolkata
18    Bangalore
21    Bangalore
22      Kolkata
23        Delhi
31      Kolkata
34       Mumbai
35    Bangalore
37      Kolkata
41      Kolkata
45    Bangalore
48    Bangalore
53        Delhi
54       Mumbai
55       Mumbai
56      Kolkata
61       Mumbai
62    Bangalore
65    Bangalore
66      Kolkata
67    Bangalore
68      Kolkata
69        Delhi
70        Delhi
71        Delhi
72      Kolkata
76    Bangalore
81        Delhi
84       Mumbai
90        Delhi
92      Kolkata
94      Kolkata
96      Kolkata
Name: city, dtype: object

In [282]:
df.loc[0, 'age'] = 25

In [283]:
df.head(1)  # see age  is  updated

   age gender  fever cough     city has_covid
0   25   Male  103.0  Mild  Kolkata        No

In [284]:
# for  iloc
# Range (0:3)
df.iloc[0:3]

# Rows 0,1,2
# (3 is NOT included)

# Exact rows ([1,2])
df.iloc[[1,2]]

# Only rows 1 and 2

# Single column
df.iloc[:, 0]
# Multiple columns
df.iloc[:, [0,1]]
# Row + Column Together
df.iloc[0:3, 0:2]
# Update values
df.iloc[0, 0] = 100   # value  updated 
df.head(1)

   age gender  fever cough     city has_covid
0  100   Male  103.0  Mild  Kolkata        No

In [285]:
# What is CRUD?
# C → Create
# R → Read
# U → Update
# D → Delete
#  1. READ  (Fully supported)

#  Both loc and iloc are mainly used for reading data

# df.loc[0:2, 'Name']
# df.iloc[0:3, 0:2]

#  Most common use

#  2. UPDATE  (Supported)

#  You can modify values

# df.loc[0, 'Age'] = 25
# df.iloc[0, 1] = 25

#  Works perfectly

#  3. CREATE  (Limited)

#  You can add new rows/columns using loc

# df.loc[5] = ['Ajay', 22]

#  loc can create
#  (!) iloc cannot create new rows

#  4. DELETE  (Not directly)

#  loc / iloc cannot delete directly

         # or 

# peration	        loc 	              iloc
# Read	           ✅     	             ✅
# Update	      ✅  	                ✅
# Create	     ✅ (limited)	       ❌
# Delete	    ❌	                  ❌

In [286]:
df.iloc[5:10,[0,2]] =55

In [287]:
df.head(11) #see age and  fever  ,rows number  5 to 9

    age  gender  fever   cough       city has_covid
0   100    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
5    55  Female   55.0    Mild  Bangalore       Yes
6    55    Male   55.0  Strong  Bangalore        No
7    55  Female   55.0  Strong     Mumbai       Yes
8    55  Female   55.0  Strong  Bangalore        No
9    55  Female   55.0    Mild      Delhi        No
10   75  Female    NaN    Mild      Delhi        No

In [288]:
# (df.iloc[5:10,[0,2]] =55)    ==  (df.loc[5:9,['age','fever']]=55)

In [289]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [290]:
df['cough'] =  df['cough'].map({'Mild':0,'Strong':1})
df['gender'] =  df['gender'].map({'Male':0,'Female':1})

In [291]:
df.sample(3)

    age  gender  fever  cough     city has_covid
40   49       1  102.0      0    Delhi        No
46   19       1  101.0      0   Mumbai        No
93   27       0  100.0      0  Kolkata       Yes

In [292]:
df['has_covid'] =  df['has_covid'].map({'Yes':1,'No':0})

In [293]:
df.sample(3)

    age  gender  fever  cough    city  has_covid
55   81       1  101.0      0  Mumbai          1
25   23       0    NaN      0  Mumbai          0
49   44       0  104.0      0  Mumbai          0

In [294]:
df.drop(columns=['city'])

    age  gender  fever  cough  has_covid
0   100       0  103.0      0          0
1    27       0  100.0      0          1
2    42       0  101.0      0          0
3    31       1   98.0      0          0
4    65       1  101.0      0          0
..  ...     ...    ...    ...        ...
95   12       1  104.0      0          0
96   51       1  101.0      1          1
97   20       1  101.0      0          0
98    5       1   98.0      1          0
99   10       1   98.0      1          1

[100 rows x 5 columns]

In [295]:
df= df.drop(columns=['city']) #  how to  remove  or delete or  drop  one  or  more  columns  
df

    age  gender  fever  cough  has_covid
0   100       0  103.0      0          0
1    27       0  100.0      0          1
2    42       0  101.0      0          0
3    31       1   98.0      0          0
4    65       1  101.0      0          0
..  ...     ...    ...    ...        ...
95   12       1  104.0      0          0
96   51       1  101.0      1          1
97   20       1  101.0      0          0
98    5       1   98.0      1          0
99   10       1   98.0      1          1

[100 rows x 5 columns]

In [296]:
df.head(2)

   age  gender  fever  cough  has_covid
0  100       0  103.0      0          0
1   27       0  100.0      0          1

In [297]:
df.sort_index() ### sort the data

# sort_index() is used when the DataFrame index becomes unsorted
# due to operations like filtering, concatenation, or shuffling.
# It arranges rows in ascending (or descending) order of index
# to make data clean, readable, and consistent.

    age  gender  fever  cough  has_covid
0   100       0  103.0      0          0
1    27       0  100.0      0          1
2    42       0  101.0      0          0
3    31       1   98.0      0          0
4    65       1  101.0      0          0
..  ...     ...    ...    ...        ...
95   12       1  104.0      0          0
96   51       1  101.0      1          1
97   20       1  101.0      0          0
98    5       1   98.0      1          0
99   10       1   98.0      1          1

[100 rows x 5 columns]

In [298]:
df = df.rename(columns =  {"cough":"updated_cough"})

In [299]:
df.sample()

    age  gender  fever  updated_cough  has_covid
94   79       0    NaN              1          1

In [300]:
df.isna().sum()

age              0
gender           0
fever            8
updated_cough    0
has_covid        0
dtype: int64

In [301]:
df.isnull().sum()

age              0
gender           0
fever            8
updated_cough    0
has_covid        0
dtype: int64

In [302]:
# Missing ValueDetected by 
#                           isna()    ?Detected by isnull()?
# NaN                         Yes                 Yes
# None                        Yes                  Yes
# NaT (datetime)              Yes                  Yes
# pd.NA                       Yes                  Yes

# Historical reasons + user convenience.
# Here's the story:

# isnull() came first — it was the original function when pandas was created.
# isna() was added later — pandas wanted to make it more intuitive, because NA is a more standard term for "missing value" in data science (especially for people coming from R language, where is.na() is used).
# They couldn't remove isnull() — because millions of people were already using it in their code. Removing it would break existing code, so they kept both.

In [303]:
df.iloc[2:5,0:4]

   age  gender  fever  updated_cough
2   42       0  101.0              0
3   31       1   98.0              0
4   65       1  101.0              0

In [304]:
df.iloc[2:5,0:4:2]

   age  fever
2   42  101.0
3   31   98.0
4   65  101.0

In [305]:
df['Age'] = df['age'].add(10) # new column is  created

In [306]:
df.head(2) 
df.shape

(100, 6)

In [307]:
df['fever'] = df['fever'].sub(100)

In [308]:
df.head(3)

   age  gender  fever  updated_cough  has_covid  Age
0  100       0    3.0              0          0  110
1   27       0    0.0              0          1   37
2   42       0    1.0              0          0   52

In [310]:
df =  df.drop(columns= ['Age'])

In [311]:
df.head(3)

   age  gender  fever  updated_cough  has_covid
0  100       0    3.0              0          0
1   27       0    0.0              0          1
2   42       0    1.0              0          0

In [314]:
df['age'] 
# df['age','fever'] this  will give  error  for  excute  2 column we  need  2-d  list 

df[['age','fever']] #   using  this method  we  can  filter the  data

    age  fever
0   100    3.0
1    27    0.0
2    42    1.0
3    31   -2.0
4    65    1.0
..  ...    ...
95   12    4.0
96   51    1.0
97   20    1.0
98    5   -2.0
99   10   -2.0

[100 rows x 2 columns]